import type { Metadata } from "next";

import "./globals.css";
export const dynamic = "force-dynamic";
import "./globals.mobile.css";
import ErrorBoundary from "./components/ErrorBoundary";
import QueryProvider from "@/providers/QueryProvider";
import ToastContainer from "./components/ToastContainer";
import GlobalModalManager from "./components/GlobalModalManager";
import { getSession } from "@/lib/auth";
import { getUserProfile } from "@/services/userService";

export const metadata: Metadata = {
  title: "Trenches v2 - Spray & Play",
  description: "Coordination Protocol for Web3",
};

import Layout from "./components/Layout";

// Check if user needs to set username (has auto-generated handle)
function checkRequiresUsername(user: any): boolean {
    if (!user?.handle) return true;
    
    const autoGeneratedPattern = /^@user_[a-f0-9]{8}$/;
    const emailPrefix = user.email?.split('@')[0];
    const hasAutoHandle = autoGeneratedPattern.test(user.handle) ||
        user.handle === `@${emailPrefix}`;
    
    return hasAutoHandle;
}

// Check if user should see onboarding (new user who just set username)
function shouldShowOnboarding(user: any): boolean {
    if (!user?.handle) return false;
    if (!user?.createdAt) return false;
    
    // Check if user was created in the last 5 minutes (fresh registration)
    const createdAt = new Date(user.createdAt);
    const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000);
    const isNewUser = createdAt > fiveMinutesAgo;
    
    return isNewUser;
}

export default async function SampleRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check user state
  let requiresUsername = false;
  let showOnboarding = false;
  let user = null;
  
  try {
    const session = await getSession();
    if (session) {
      user = await getUserProfile(session.id);
      requiresUsername = checkRequiresUsername(user);
      showOnboarding = shouldShowOnboarding(user);
    }
  } catch (error) {
    console.error('[Layout] Failed to check user:', error);
  }

  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <ErrorBoundary>
            <ToastContainer />
            <GlobalModalManager 
              requiresUsername={requiresUsername} 
              showOnboarding={showOnboarding}
              user={user} 
            />
            <Layout>{children}</Layout>
          </ErrorBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
// Trigger redeploy: Sat Jan 31 11:44:06 WAT 2026
