import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getSupabaseUser } from '@/lib/auth';
import { validateReferralCode, applyReferral } from '@/services/referral.service';

/**
 * GET /api/user/username?check=<username>
 * Check if a username is available
 */
export async function GET(request: Request) {
    const { searchParams } = new URL(request.url);
    const username = searchParams.get('check');

    if (!username) {
        return NextResponse.json({ error: 'Username required' }, { status: 400 });
    }

    // Validate format (alphanumeric, underscore, 3-20 chars)
    const usernameRegex = /^[a-zA-Z0-9_]{3,20}$/;
    if (!usernameRegex.test(username)) {
        return NextResponse.json({
            available: false,
            reason: 'Username must be 3-20 characters, alphanumeric and underscores only'
        });
    }

    // Check if username exists (case-insensitive)
    const existing = await prisma.user.findFirst({
        where: {
            handle: {
                equals: `@${username}`,
                mode: 'insensitive'
            }
        }
    });

    return NextResponse.json({
        available: !existing,
        reason: existing ? 'Username already taken' : null
    });
}

/**
 * POST /api/user/username
 * Set username for the current user (only if they haven't set one yet)
 */
export async function POST(request: Request) {
    const supabaseUser = await getSupabaseUser();
    if (!supabaseUser) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { username, referralCode } = await request.json();

    if (!username) {
        return NextResponse.json({ error: 'Username required' }, { status: 400 });
    }

    // Validate format
    const usernameRegex = /^[a-zA-Z0-9_]{3,20}$/;
    if (!usernameRegex.test(username)) {
        return NextResponse.json({
            success: false,
            error: 'Username must be 3-20 characters, alphanumeric and underscores only'
        }, { status: 400 });
    }

    // Find user
    let user = await prisma.user.findUnique({
        where: { supabaseId: supabaseUser.id }
    });

    // Check if user already has a custom username (not auto-generated)
    const autoGeneratedPattern = /^@user_[a-f0-9]{8}$/;
    const emailPattern = /^@[a-zA-Z0-9._-]+$/; // Email-derived handles

    if (user && !autoGeneratedPattern.test(user.handle) && !user.handle.startsWith('@user_')) {
        // Check if handle looks like it was manually set vs derived from email
        const emailPrefix = supabaseUser.email?.split('@')[0];
        if (user.handle !== `@${emailPrefix}`) {
            return NextResponse.json({
                success: false,
                error: 'Username already set'
            }, { status: 400 });
        }
    }

    // Check uniqueness (case-insensitive)
    const existing = await prisma.user.findFirst({
        where: {
            handle: {
                equals: `@${username}`,
                mode: 'insensitive'
            },
            NOT: { supabaseId: supabaseUser.id }
        }
    });

    if (existing) {
        return NextResponse.json({
            success: false,
            error: 'Username already taken'
        }, { status: 409 });
    }

    // Create or update user with username
    if (!user) {
        user = await prisma.user.create({
            data: {
                supabaseId: supabaseUser.id,
                email: supabaseUser.email,
                handle: `@${username}`,
            }
        });
    } else {
        user = await prisma.user.update({
            where: { id: user.id },
            data: { handle: `@${username}` }
        });
    }

    // Apply referral if provided
    if (referralCode) {
        try {
            const validation = await validateReferralCode(referralCode);
            if (validation.valid && validation.referrer) {
                await applyReferral(user.id, validation.referrer.id);
            }
        } catch (err) {
            console.error('Error applying referral during username setup:', err);
            // Don't fail the whole request just because referral application failed
        }
    }

    return NextResponse.json({
        success: true,
        user: {
            id: user.id,
            handle: user.handle,
            email: user.email
        }
    });
}
