import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { isAdminEmail } from '@/lib/admin-auth';

export async function GET(request: Request) {
    const { searchParams, origin } = new URL(request.url);
    const code = searchParams.get('code');
    const next = searchParams.get('next') ?? '/dashboard';

    // Check if this is an admin login flow
    const isAdminFlow = next === '/admin' || next.startsWith('/admin');

    if (code) {
        const supabase = await createClient();
        const { data, error } = await supabase.auth.exchangeCodeForSession(code);

        if (!error && data.user) {
            // Handle admin login flow
            if (isAdminFlow) {
                if (isAdminEmail(data.user.email)) {
                    // Admin verified - redirect to admin panel
                    console.log(`Admin login: ${data.user.email}`);
                    return NextResponse.redirect(`${origin}/admin`);
                } else {
                    // Not an admin - sign out and redirect with error
                    await supabase.auth.signOut();
                    console.warn(`Non-admin login attempt: ${data.user.email}`);
                    return NextResponse.redirect(`${origin}/admin/login?error=unauthorized`);
                }
            }

            // Regular user flow
            // Check if user exists and has a proper username
            const existingUser = await prisma.user.findUnique({
                where: { supabaseId: data.user.id }
            });

            if (!existingUser) {
                // New user - redirect to registration to pick username
                return NextResponse.redirect(`${origin}/register`);
            }

            // Check if user has an auto-generated handle that needs updating
            const autoGeneratedPattern = /^@user_[a-f0-9]{8}$/;
            const emailPrefix = data.user.email?.split('@')[0];
            const hasAutoHandle = autoGeneratedPattern.test(existingUser.handle) ||
                existingUser.handle === `@${emailPrefix}`;

            if (hasAutoHandle) {
                // User never picked a custom username
                return NextResponse.redirect(`${origin}/register`);
            }

            return NextResponse.redirect(`${origin}${next}`);
        }
    }

    // Return to login page with error
    const errorRedirect = isAdminFlow ? '/admin/login' : '/login';
    return NextResponse.redirect(`${origin}${errorRedirect}?error=auth_failed`);
}
