import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { prisma } from '@/lib/db';
import { isAdminEmail } from '@/lib/admin-auth';

export async function GET(request: Request) {
    try {
        const { searchParams, origin } = new URL(request.url);
        const code = searchParams.get('code');
        const next = searchParams.get('next') ?? '/sample-v2/dashboard-v2';

        console.log('[Auth Callback] Triggered:', { code: code?.slice(0, 10) + '...', next, origin });

        // Check if this is an admin login flow
        const isAdminFlow = next === '/admin' || next.startsWith('/admin');

        if (!code) {
            console.error('[Auth Callback] No code provided');
            const errorRedirect = isAdminFlow ? '/admin/login' : '/login';
            return NextResponse.redirect(`${origin}${errorRedirect}?error=auth_failed`);
        }

        const supabase = await createClient();
        console.log('[Auth Callback] Supabase client created');

        const { data, error } = await supabase.auth.exchangeCodeForSession(code);
        console.log('[Auth Callback] Exchange result:', { hasUser: !!data.user, error: error?.message, hasSession: !!data.session });

        if (error || !data.user) {
            console.error('[Auth Callback] Exchange error:', error);
            const errorRedirect = isAdminFlow ? '/admin/login' : '/login';
            return NextResponse.redirect(`${origin}${errorRedirect}?error=auth_failed`);
        }

        console.log('[Auth Callback] User authenticated:', data.user.email);
        
        // Debug: Check what cookies are set after exchange
        const cookieStore = await cookies();
        const allCookies = cookieStore.getAll();
        console.log('[Auth Callback] Cookies after exchange:', allCookies.map(c => c.name));

        // Handle admin login flow
        if (isAdminFlow) {
            if (isAdminEmail(data.user.email)) {
                console.log(`Admin login: ${data.user.email}`);
                return NextResponse.redirect(`${origin}/admin`);
            } else {
                await supabase.auth.signOut();
                console.warn(`Non-admin login attempt: ${data.user.email}`);
                return NextResponse.redirect(`${origin}/admin/login?error=unauthorized`);
            }
        }

        // Regular user flow
        try {
            // Check if user exists
            const existingUser = await prisma.user.findUnique({
                where: { supabaseId: data.user.id }
            });

            if (!existingUser) {
                console.log('New user - redirecting to registration');
                return NextResponse.redirect(`${origin}/register`);
            }

            // Check if user needs to complete registration
            const autoGeneratedPattern = /^@user_[a-f0-9]{8}$/;
            const emailPrefix = data.user.email?.split('@')[0];
            const hasAutoHandle = autoGeneratedPattern.test(existingUser.handle) ||
                existingUser.handle === `@${emailPrefix}`;

            if (hasAutoHandle) {
                console.log('User needs to complete registration');
                return NextResponse.redirect(`${origin}/register`);
            }

            console.log('Existing user - redirecting to dashboard');
            // Create redirect response and ensure cookies are preserved
            const redirectResponse = NextResponse.redirect(`${origin}${next}`);
            
            // Copy all cookies to the redirect response to ensure session persists
            const finalCookieStore = await cookies();
            finalCookieStore.getAll().forEach((cookie) => {
                redirectResponse.cookies.set(cookie.name, cookie.value);
            });
            
            return redirectResponse;
        } catch (dbError: any) {
            console.error('Database error:', dbError);
            // If DB fails, still redirect to dashboard - user is authenticated
            return NextResponse.redirect(`${origin}${next}`);
        }
    } catch (err: any) {
        console.error('Callback error:', err);
        return NextResponse.redirect(`${process.env.NEXT_PUBLIC_SITE_URL || 'https://trenches-dapp.vercel.app'}/login?error=auth_failed`);
    }
}
